(deftheme doom-nord-modified
  "Created 2020-12-26.")

(custom-theme-set-faces
 'doom-nord-modified
 '(default ((t (:family "Roboto Mono" :foundry "outline" :width normal :height 100 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#ECEFF4" :background "#2E3440" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#81A1C1"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#81A1C1"))))
 '(highlight ((t (:foreground "#191C25" :background "#81A1C1"))))
 '(region ((t (:extend t :background "#434C5E"))))
 '(shadow ((t (:foreground "#4C566A"))))
 '(secondary-selection ((t (:extend t :background "#434C5E"))))
 '(trailing-whitespace ((t (:background "#BF616A"))))
 '(font-lock-builtin-face ((t (:foreground "#81A1C1"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#6f7787"))))
 '(font-lock-constant-face ((t (:foreground "#81A1C1"))))
 '(font-lock-doc-face ((t (:foreground "#78808f" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:foreground "#8FBCBB"))))
 '(font-lock-keyword-face ((t (:foreground "#81A1C1"))))
 '(font-lock-negation-char-face ((t (:foreground "#81A1C1" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#81A1C1" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#81A1C1" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#81A1C1" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#A3BE8C"))))
 '(font-lock-type-face ((t (:foreground "#8FBCBB"))))
 '(font-lock-variable-name-face ((t (:foreground "#D8DEE9"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#81A1C1"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#434C5E" :inherit (default)))))
 '(header-line ((t (:foreground "#ECEFF4" :background "#2E3440"))))
 '(tooltip ((t (:foreground "#ECEFF4" :background "#373E4C"))))
 '(mode-line ((t (:box nil :background "#242832"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#81A1C1"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#9099AB" :background "#292e39"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#191C25" :background "#BF616A"))))
 '(lazy-highlight ((t (:weight bold :foreground "#F0F4FC" :background "#5E81AC"))))
 '(match ((t (:weight bold :foreground "#A3BE8C" :background "#191C25"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(dired-subtree-depth-1-face ((t (:background "old lace"))))
 '(dired-subtree-depth-2-face ((t (:background "gray95"))))
 '(dired-subtree-depth-3-face ((t (:background "old lace"))))
 '(dired-subtree-depth-4-face ((t (:background "gray95"))))
 '(dired-subtree-depth-5-face ((t (:background "old lace"))))
 '(dired-subtree-depth-6-face ((t (:background "gray95"))))
 '(dired-subtree-depth-7-face ((t (:background "old lace"))))
 '(dired-subtree-depth-8-face ((t (:background "gray95"))))
 '(line-number ((t (:inherit default :foreground "gray80"))))
 '(org-block ((t (:extend t :background "gray95" :height 100 :family "Fira Code"))))
 '(org-block-begin-line ((t (:foreground "slateblue" :underline nil))))
 '(org-block-end-line ((t (:foreground "slateblue" :overline nil))))
 '(org-document-info-keyword ((t (:foreground "slateblue"))))
 '(org-document-title ((t (:overline nil :underline nil :weight bold :height 2.8 :family "Century"))))
 '(org-drawer ((t (:foreground "grey50"))))
 '(org-ellipsis ((t (:foreground "gray60"  :box nil :underline nil :overline nil :weight normal :height 80))))
 '(org-level-1 ((t (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(org-level-2 ((t (:height 1.0 :weight bold ))))
 '(org-level-3 ((t (:height 1.0 :weight bold ))))
 '(org-level-4 ((t (:height 1.0 :weight bold ))))
 '(org-level-5 ((t (:height 1.0 :weight bold ))))
 '(org-level-6 ((t (:height 1.0 :weight bold ))))
 '(org-level-7 ((t (:height 1.0 :weight bold ))))
 '(org-level-8 ((t (:height 1.0 :weight bold ))))
 '(org-meta-line ((t (:foreground slateblue))))
 '(org-table ((t (:foreground royalblue))))
 )

(provide-theme 'doom-nord-modified)
