#+TITLE: ConfWiki Inbox
#+Last Saved: <Nov 13, 2019>


** unicode

http://xahlee.info/comp/a_emoji_tale.html
http://ergoemacs.org/emacs/emacs_n_unicode.html

** Full text search on org files

*** Lucene lisp!                                                                          :useful:promising:

http://rudolfochrist.github.io/blog/2015/08/19/on-indexing-org-files/

Looks promising and complete solution!

- mdfind

https://www.cliki.net/Montezuma

*** recoll                                                                                :related:
https://oremacs.com/2015/07/27/counsel-recoll/

*** full-text-search to website                                                           :related:
https://medium.com/dev-channel/how-to-add-full-text-search-to-your-website-4e9c80ce2bf4

**** lunr.js
https://lunrjs.com/guides/core_concepts.html

** leaf.el - another package manger like use-package
https://github.com/conao3/leaf.el

** reveal.js + ox-reveal excellent presentation from org mode
https://opensource.com/article/18/2/how-create-slides-emacs-org-mode-and-revealjs

https://github.com/FormidableLabs/spectacle 7.8 Stars!

** emacs fringes and margins
(set-window-margins)
(set-window-margins WINDOW LEFT-WIDTH &optional RIGHT-WIDTH)

(with-current-buffer (window-buffer WINDOW))

list of [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Standard-Hooks.html][hooks]]


(defun my-set-margins ()
  "Set margins in current buffer."
  (setq left-margin-width 24)
  (setq right-margin-width 24))


** contribute to page-break (2019-08-25 Sun)

added this to fix the page-break.el!
#+begin_src emacs-lisp
(width (if (boundp 'left-margin)
           (- width left-margin)
         width))
(width (if (boundp 'right-margin)
           (- width right-margin)
         width))
#+end_src

** org-table background color
https://emacs.stackexchange.com/questions/7375/can-i-format-cells-in-an-org-mode-table-differently-depending-on-a-formula

** ivy reference
https://oremacs.com/swiper/#required-arguments-for-ivy-read

** Literate dot files
https://writepermission.com/introducing-literate-dotfiles.html
https://gitlab.com/to1ne/literate-dotfiles/blob/master/Makefile#L26-30
https://github.com/kwpav/dotfiles

use stow!

#+begin_src conf
#+TITLE:      Toon's i3 configuration
#+AUTHOR:     Toon Claes
#+KEYWORDS:   toon claes i3 wm config
#+STARTUP:    showall
#+PROPERTY:   header-args+ :comments both
#+PROPERTY:   header-args+ :mkdirp yes
#+PROPERTY:   header-args+ :tangle "~/.config/i3/config"
-----
#+end_src

** GTD Howardabrams
http://howardism.org/Technical/Emacs/getting-more-boxes-done.html
https://gitlab.com/howardabrams/spacemacs.d/blob/master/elisp/boxes.el

** counsel recoll - a full text search with xapian core

https://github.com/koniu/recoll-webui  - a very nice ui!

https://github.com/alraban/org-recoll
https://oremacs.com/2015/07/27/counsel-recoll/

https://www.emacswiki.org/emacs/AnythingSources#toc58


** Huge collection of config links

https://github.com/emacs-tw/awesome-emacs
https://github.com/pierre-lecocq/emacs4developers

* scratch

https://ternjs.net/  - intelligent javascript editor!

(straight-use-package 'el-patch)

(setq initial-buffer-choice 'counsel-recentf)
